//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDStashViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} - ({2}) {4}")]
        public string ExportFormat {
            get {
                return ((string)(this["ExportFormat"]));
            }
            set {
                this["ExportFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>&lt;none&gt;</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FileHistory {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FileHistory"]));
            }
            set {
                this["FileHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ListCfgFile {
            get {
                return ((string)(this["ListCfgFile"]));
            }
            set {
                this["ListCfgFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfColumnInformation xmlns:xsd=\"htt" +
            "p://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-insta" +
            "nce\">\r\n  <ColumnInformation>\r\n    <Header xsi:type=\"xsd:string\">Link</Header>\r\n " +
            "   <PropertyPath>Url</PropertyPath>\r\n    <SortDirection xsi:nil=\"true\" />\r\n    <" +
            "DisplayIndex>0</DisplayIndex>\r\n    <WidthValue>40</WidthValue>\r\n    <WidthType>P" +
            "ixel</WidthType>\r\n    <SortMemberPath>Url</SortMemberPath>\r\n    <IsVisible>true<" +
            "/IsVisible>\r\n  </ColumnInformation>\r\n  <ColumnInformation>\r\n    <Header xsi:type" +
            "=\"xsd:string\">Name</Header>\r\n    <PropertyPath>Name</PropertyPath>\r\n    <SortDir" +
            "ection xsi:nil=\"true\" />\r\n    <DisplayIndex>1</DisplayIndex>\r\n    <WidthValue>19" +
            "2</WidthValue>\r\n    <WidthType>Auto</WidthType>\r\n    <SortMemberPath>Name</SortM" +
            "emberPath>\r\n    <IsVisible>true</IsVisible>\r\n  </ColumnInformation>\r\n  <ColumnIn" +
            "formation>\r\n    <Header xsi:type=\"xsd:string\">Class</Header>\r\n    <PropertyPath>" +
            "Class</PropertyPath>\r\n    <SortDirection xsi:nil=\"true\" />\r\n    <DisplayIndex>2<" +
            "/DisplayIndex>\r\n    <WidthValue>70</WidthValue>\r\n    <WidthType>Pixel</WidthType" +
            ">\r\n    <SortMemberPath>Class</SortMemberPath>\r\n    <IsVisible>true</IsVisible>\r\n" +
            "  </ColumnInformation>\r\n  <ColumnInformation>\r\n    <Header xsi:type=\"xsd:string\"" +
            ">SubCategory</Header>\r\n    <PropertyPath>SubCategory</PropertyPath>\r\n    <SortDi" +
            "rection xsi:nil=\"true\" />\r\n    <DisplayIndex>3</DisplayIndex>\r\n    <WidthValue>7" +
            "0</WidthValue>\r\n    <WidthType>Pixel</WidthType>\r\n    <SortMemberPath>SubCategor" +
            "y</SortMemberPath>\r\n    <IsVisible>true</IsVisible>\r\n  </ColumnInformation>\r\n  <" +
            "ColumnInformation>\r\n    <Header xsi:type=\"xsd:string\">Category</Header>\r\n    <Pr" +
            "opertyPath>Category</PropertyPath>\r\n    <SortDirection xsi:nil=\"true\" />\r\n    <D" +
            "isplayIndex>4</DisplayIndex>\r\n    <WidthValue>70</WidthValue>\r\n    <WidthType>Pi" +
            "xel</WidthType>\r\n    <SortMemberPath>Category</SortMemberPath>\r\n    <IsVisible>t" +
            "rue</IsVisible>\r\n  </ColumnInformation>\r\n  <ColumnInformation>\r\n    <Header xsi:" +
            "type=\"xsd:string\">LevelRequirement</Header>\r\n    <PropertyPath>LevelRequirement<" +
            "/PropertyPath>\r\n    <SortDirection xsi:nil=\"true\" />\r\n    <DisplayIndex>5</Displ" +
            "ayIndex>\r\n    <WidthValue>70</WidthValue>\r\n    <WidthType>Pixel</WidthType>\r\n   " +
            " <SortMemberPath>LevelRequirement</SortMemberPath>\r\n    <IsVisible>true</IsVisib" +
            "le>\r\n  </ColumnInformation>\r\n  <ColumnInformation>\r\n    <Header xsi:type=\"xsd:st" +
            "ring\">IsEmpowered</Header>\r\n    <PropertyPath>IsEmpowered</PropertyPath>\r\n    <S" +
            "ortDirection xsi:nil=\"true\" />\r\n    <DisplayIndex>6</DisplayIndex>\r\n    <WidthVa" +
            "lue>48</WidthValue>\r\n    <WidthType>Auto</WidthType>\r\n    <SortMemberPath>IsEmpo" +
            "wered</SortMemberPath>\r\n    <IsVisible>true</IsVisible>\r\n  </ColumnInformation>\r" +
            "\n  <ColumnInformation>\r\n    <Header xsi:type=\"xsd:string\">Bag</Header>\r\n    <Pro" +
            "pertyPath>Bag</PropertyPath>\r\n    <SortDirection xsi:nil=\"true\" />\r\n    <Display" +
            "Index>7</DisplayIndex>\r\n    <WidthValue>68</WidthValue>\r\n    <WidthType>Auto</Wi" +
            "dthType>\r\n    <SortMemberPath>Bag</SortMemberPath>\r\n    <IsVisible>true</IsVisib" +
            "le>\r\n  </ColumnInformation>\r\n  <ColumnInformation>\r\n    <Header xsi:type=\"xsd:st" +
            "ring\">StashFile</Header>\r\n    <PropertyPath>StashFile</PropertyPath>\r\n    <SortD" +
            "irection xsi:nil=\"true\" />\r\n    <DisplayIndex>27</DisplayIndex>\r\n    <WidthValue" +
            ">342</WidthValue>\r\n    <WidthType>Auto</WidthType>\r\n    <SortMemberPath>StashFil" +
            "e</SortMemberPath>\r\n    <IsVisible>true</IsVisible>\r\n  </ColumnInformation>\r\n  <" +
            "ColumnInformation>\r\n    <Header xsi:type=\"xsd:string\">FriendlyName</Header>\r\n   " +
            " <PropertyPath>FriendlyName</PropertyPath>\r\n    <SortDirection xsi:nil=\"true\" />" +
            "\r\n    <DisplayIndex>8</DisplayIndex>\r\n    <WidthValue>126</WidthValue>\r\n    <Wid" +
            "thType>Auto</WidthType>\r\n    <SortMemberPath>FriendlyName</SortMemberPath>\r\n    " +
            "<IsVisible>true</IsVisible>\r\n  </ColumnInformation>\r\n  <ColumnInformation>\r\n    " +
            "<Header xsi:type=\"xsd:string\">DbrFileName</Header>\r\n    <PropertyPath>DbrFileNam" +
            "e</PropertyPath>\r\n    <SortDirection xsi:nil=\"true\" />\r\n    <DisplayIndex>9</Dis" +
            "playIndex>\r\n    <WidthValue>126</WidthValue>\r\n    <WidthType>Auto</WidthType>\r\n " +
            "   <SortMemberPath>DbrFileName</SortMemberPath>\r\n    <IsVisible>true</IsVisible>" +
            "\r\n  </ColumnInformation>\r\n  <ColumnInformation>\r\n    <Header xsi:type=\"xsd:strin" +
            "g\">Tag</Header>\r\n    <PropertyPath>Tag</PropertyPath>\r\n    <SortDirection xsi:ni" +
            "l=\"true\" />\r\n    <DisplayIndex>10</DisplayIndex>\r\n    <WidthValue>156</WidthValu" +
            "e>\r\n    <WidthType>Auto</WidthType>\r\n    <SortMemberPath>Tag</SortMemberPath>\r\n " +
            "   <IsVisible>true</IsVisible>\r\n  </ColumnInformation>\r\n  <ColumnInformation>\r\n " +
            "   <Header xsi:type=\"xsd:string\">baseName</Header>\r\n    <PropertyPath>baseName</" +
            "PropertyPath>\r\n    <SortDirection xsi:nil=\"true\" />\r\n    <DisplayIndex>11</Displ" +
            "ayIndex>\r\n    <WidthValue>20</WidthValue>\r\n    <WidthType>Auto</WidthType>\r\n    " +
            "<SortMemberPath>baseName</SortMemberPath>\r\n    <IsVisible>false</IsVisible>\r\n  <" +
            "/ColumnInformation>\r\n  <ColumnInformation>\r\n    <Header xsi:type=\"xsd:string\">st" +
            "ackCount</Header>\r\n    <PropertyPath>stackCount</PropertyPath>\r\n    <SortDirecti" +
            "on xsi:nil=\"true\" />\r\n    <DisplayIndex>12</DisplayIndex>\r\n    <WidthValue>20</W" +
            "idthValue>\r\n    <WidthType>Auto</WidthType>\r\n    <SortMemberPath>stackCount</Sor" +
            "tMemberPath>\r\n    <IsVisible>false</IsVisible>\r\n  </ColumnInformation>\r\n  <Colum" +
            "nInformation>\r\n    <Header xsi:type=\"xsd:string\">prefixName</Header>\r\n    <Prope" +
            "rtyPath>prefixName</PropertyPath>\r\n    <SortDirection xsi:nil=\"true\" />\r\n    <Di" +
            "splayIndex>13</DisplayIndex>\r\n    <WidthValue>20</WidthValue>\r\n    <WidthType>Au" +
            "to</WidthType>\r\n    <SortMemberPath>prefixName</SortMemberPath>\r\n    <IsVisible>" +
            "false</IsVisible>\r\n  </ColumnInformation>\r\n  <ColumnInformation>\r\n    <Header xs" +
            "i:type=\"xsd:string\">suffixName</Header>\r\n    <PropertyPath>suffixName</PropertyP" +
            "ath>\r\n    <SortDirection xsi:nil=\"true\" />\r\n    <DisplayIndex>14</DisplayIndex>\r" +
            "\n    <WidthValue>20</WidthValue>\r\n    <WidthType>Auto</WidthType>\r\n    <SortMemb" +
            "erPath>suffixName</SortMemberPath>\r\n    <IsVisible>false</IsVisible>\r\n  </Column" +
            "Information>\r\n  <ColumnInformation>\r\n    <Header xsi:type=\"xsd:string\">modifierN" +
            "ame</Header>\r\n    <PropertyPath>modifierName</PropertyPath>\r\n    <SortDirection " +
            "xsi:nil=\"true\" />\r\n    <DisplayIndex>15</DisplayIndex>\r\n    <WidthValue>20</Widt" +
            "hValue>\r\n    <WidthType>Auto</WidthType>\r\n    <SortMemberPath>modifierName</Sort" +
            "MemberPath>\r\n    <IsVisible>false</IsVisible>\r\n  </ColumnInformation>\r\n  <Column" +
            "Information>\r\n    <Header xsi:type=\"xsd:string\">transmuteName</Header>\r\n    <Pro" +
            "pertyPath>transmuteName</PropertyPath>\r\n    <SortDirection xsi:nil=\"true\" />\r\n  " +
            "  <DisplayIndex>16</DisplayIndex>\r\n    <WidthValue>20</WidthValue>\r\n    <WidthTy" +
            "pe>Auto</WidthType>\r\n    <SortMemberPath>transmuteName</SortMemberPath>\r\n    <Is" +
            "Visible>false</IsVisible>\r\n  </ColumnInformation>\r\n  <ColumnInformation>\r\n    <H" +
            "eader xsi:type=\"xsd:string\">seed</Header>\r\n    <PropertyPath>seed</PropertyPath>" +
            "\r\n    <SortDirection xsi:nil=\"true\" />\r\n    <DisplayIndex>17</DisplayIndex>\r\n   " +
            " <WidthValue>20</WidthValue>\r\n    <WidthType>Auto</WidthType>\r\n    <SortMemberPa" +
            "th>seed</SortMemberPath>\r\n    <IsVisible>false</IsVisible>\r\n  </ColumnInformatio" +
            "n>\r\n  <ColumnInformation>\r\n    <Header xsi:type=\"xsd:string\">relicName</Header>\r" +
            "\n    <PropertyPath>relicName</PropertyPath>\r\n    <SortDirection xsi:nil=\"true\" /" +
            ">\r\n    <DisplayIndex>18</DisplayIndex>\r\n    <WidthValue>20</WidthValue>\r\n    <Wi" +
            "dthType>Auto</WidthType>\r\n    <SortMemberPath>relicName</SortMemberPath>\r\n    <I" +
            "sVisible>false</IsVisible>\r\n  </ColumnInformation>\r\n  <ColumnInformation>\r\n    <" +
            "Header xsi:type=\"xsd:string\">relicBonus</Header>\r\n    <PropertyPath>relicBonus</" +
            "PropertyPath>\r\n    <SortDirection xsi:nil=\"true\" />\r\n    <DisplayIndex>19</Displ" +
            "ayIndex>\r\n    <WidthValue>20</WidthValue>\r\n    <WidthType>Auto</WidthType>\r\n    " +
            "<SortMemberPath>relicBonus</SortMemberPath>\r\n    <IsVisible>false</IsVisible>\r\n " +
            " </ColumnInformation>\r\n  <ColumnInformation>\r\n    <Header xsi:type=\"xsd:string\">" +
            "relicSeed</Header>\r\n    <PropertyPath>relicSeed</PropertyPath>\r\n    <SortDirecti" +
            "on xsi:nil=\"true\" />\r\n    <DisplayIndex>20</DisplayIndex>\r\n    <WidthValue>20</W" +
            "idthValue>\r\n    <WidthType>Auto</WidthType>\r\n    <SortMemberPath>relicSeed</Sort" +
            "MemberPath>\r\n    <IsVisible>false</IsVisible>\r\n  </ColumnInformation>\r\n  <Column" +
            "Information>\r\n    <Header xsi:type=\"xsd:string\">augmentName</Header>\r\n    <Prope" +
            "rtyPath>augmentName</PropertyPath>\r\n    <SortDirection xsi:nil=\"true\" />\r\n    <D" +
            "isplayIndex>21</DisplayIndex>\r\n    <WidthValue>20</WidthValue>\r\n    <WidthType>A" +
            "uto</WidthType>\r\n    <SortMemberPath>augmentName</SortMemberPath>\r\n    <IsVisibl" +
            "e>false</IsVisible>\r\n  </ColumnInformation>\r\n  <ColumnInformation>\r\n    <Header " +
            "xsi:type=\"xsd:string\">unknown</Header>\r\n    <PropertyPath>unknown</PropertyPath>" +
            "\r\n    <SortDirection xsi:nil=\"true\" />\r\n    <DisplayIndex>22</DisplayIndex>\r\n   " +
            " <WidthValue>20</WidthValue>\r\n    <WidthType>Auto</WidthType>\r\n    <SortMemberPa" +
            "th>unknown</SortMemberPath>\r\n    <IsVisible>false</IsVisible>\r\n  </ColumnInforma" +
            "tion>\r\n  <ColumnInformation>\r\n    <Header xsi:type=\"xsd:string\">augmentSeed</Hea" +
            "der>\r\n    <PropertyPath>augmentSeed</PropertyPath>\r\n    <SortDirection xsi:nil=\"" +
            "true\" />\r\n    <DisplayIndex>23</DisplayIndex>\r\n    <WidthValue>20</WidthValue>\r\n" +
            "    <WidthType>Auto</WidthType>\r\n    <SortMemberPath>augmentSeed</SortMemberPath" +
            ">\r\n    <IsVisible>false</IsVisible>\r\n  </ColumnInformation>\r\n  <ColumnInformatio" +
            "n>\r\n    <Header xsi:type=\"xsd:string\">var1</Header>\r\n    <PropertyPath>var1</Pro" +
            "pertyPath>\r\n    <SortDirection xsi:nil=\"true\" />\r\n    <DisplayIndex>24</DisplayI" +
            "ndex>\r\n    <WidthValue>20</WidthValue>\r\n    <WidthType>Auto</WidthType>\r\n    <So" +
            "rtMemberPath>var1</SortMemberPath>\r\n    <IsVisible>false</IsVisible>\r\n  </Column" +
            "Information>\r\n  <ColumnInformation>\r\n    <Header xsi:type=\"xsd:string\">xOffset</" +
            "Header>\r\n    <PropertyPath>xOffset</PropertyPath>\r\n    <SortDirection xsi:nil=\"t" +
            "rue\" />\r\n    <DisplayIndex>25</DisplayIndex>\r\n    <WidthValue>20</WidthValue>\r\n " +
            "   <WidthType>Auto</WidthType>\r\n    <SortMemberPath>xOffset</SortMemberPath>\r\n  " +
            "  <IsVisible>false</IsVisible>\r\n  </ColumnInformation>\r\n  <ColumnInformation>\r\n " +
            "   <Header xsi:type=\"xsd:string\">yOffset</Header>\r\n    <PropertyPath>yOffset</Pr" +
            "opertyPath>\r\n    <SortDirection xsi:nil=\"true\" />\r\n    <DisplayIndex>26</Display" +
            "Index>\r\n    <WidthValue>20</WidthValue>\r\n    <WidthType>Auto</WidthType>\r\n    <S" +
            "ortMemberPath>yOffset</SortMemberPath>\r\n    <IsVisible>false</IsVisible>\r\n  </Co" +
            "lumnInformation>\r\n  <ColumnInformation>\r\n    <Header xsi:type=\"xsd:string\">Empow" +
            "eredName</Header>\r\n    <PropertyPath>EmpoweredName</PropertyPath>\r\n    <SortDire" +
            "ction xsi:nil=\"true\" />\r\n    <DisplayIndex>28</DisplayIndex>\r\n    <WidthValue>23" +
            "8</WidthValue>\r\n    <WidthType>Auto</WidthType>\r\n    <SortMemberPath>EmpoweredNa" +
            "me</SortMemberPath>\r\n    <IsVisible>false</IsVisible>\r\n  </ColumnInformation>\r\n " +
            " <ColumnInformation>\r\n    <Header xsi:type=\"xsd:string\">Count</Header>\r\n    <Pro" +
            "pertyPath>Count</PropertyPath>\r\n    <SortDirection xsi:nil=\"true\" />\r\n    <Displ" +
            "ayIndex>29</DisplayIndex>\r\n    <WidthValue>80</WidthValue>\r\n    <WidthType>Auto<" +
            "/WidthType>\r\n    <SortMemberPath>Count</SortMemberPath>\r\n    <IsVisible>false</I" +
            "sVisible>\r\n  </ColumnInformation>\r\n  <ColumnInformation>\r\n    <Header xsi:type=\"" +
            "xsd:string\">Url</Header>\r\n    <PropertyPath>Url</PropertyPath>\r\n    <SortDirecti" +
            "on xsi:nil=\"true\" />\r\n    <DisplayIndex>30</DisplayIndex>\r\n    <WidthValue>537</" +
            "WidthValue>\r\n    <WidthType>Auto</WidthType>\r\n    <SortMemberPath>Url</SortMembe" +
            "rPath>\r\n    <IsVisible>true</IsVisible>\r\n  </ColumnInformation>\r\n</ArrayOfColumn" +
            "Information>")]
        public string ColumnLayout {
            get {
                return ((string)(this["ColumnLayout"]));
            }
            set {
                this["ColumnLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection FilterHistory {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FilterHistory"]));
            }
            set {
                this["FilterHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} ({1})")]
        public string ExportGroupFormat {
            get {
                return ((string)(this["ExportGroupFormat"]));
            }
            set {
                this["ExportGroupFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExportHeaderFormat {
            get {
                return ((string)(this["ExportHeaderFormat"]));
            }
            set {
                this["ExportHeaderFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExportFooterFormat {
            get {
                return ((string)(this["ExportFooterFormat"]));
            }
            set {
                this["ExportFooterFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExportUseIndent {
            get {
                return ((bool)(this["ExportUseIndent"]));
            }
            set {
                this["ExportUseIndent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExportShouldIgnoreGrouping {
            get {
                return ((bool)(this["ExportShouldIgnoreGrouping"]));
            }
            set {
                this["ExportShouldIgnoreGrouping"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExportShouldIgnoreDuplicates {
            get {
                return ((bool)(this["ExportShouldIgnoreDuplicates"]));
            }
            set {
                this["ExportShouldIgnoreDuplicates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExportGroupFooterFormat {
            get {
                return ((string)(this["ExportGroupFooterFormat"]));
            }
            set {
                this["ExportGroupFooterFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExportShouldUseUrl {
            get {
                return ((bool)(this["ExportShouldUseUrl"]));
            }
            set {
                this["ExportShouldUseUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExtractedRootFolder {
            get {
                return ((string)(this["ExtractedRootFolder"]));
            }
            set {
                this["ExtractedRootFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExportShouldIgnoreDontExport {
            get {
                return ((bool)(this["ExportShouldIgnoreDontExport"]));
            }
            set {
                this["ExportShouldIgnoreDontExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShouldResolveAffixes {
            get {
                return ((bool)(this["ShouldResolveAffixes"]));
            }
            set {
                this["ShouldResolveAffixes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseAlternateAffixFormat {
            get {
                return ((bool)(this["UseAlternateAffixFormat"]));
            }
            set {
                this["UseAlternateAffixFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ResourceFolder {
            get {
                return ((string)(this["ResourceFolder"]));
            }
            set {
                this["ResourceFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GSTFolder {
            get {
                return ((string)(this["GSTFolder"]));
            }
            set {
                this["GSTFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncludePlayerCharacters {
            get {
                return ((bool)(this["IncludePlayerCharacters"]));
            }
            set {
                this["IncludePlayerCharacters"] = value;
            }
        }
    }
}
